experiment_name: "kobert test"
framework: "pytorch"
model_name: "kobert"
pretrained_model_name: "checkpoints/kobert_test_20250506_144826"
num_labels: 5
max_length: 256
batch_size: 32
epochs: 5
lr: 2e-5
val_ratio: 0.2
test_ratio: 0.1
save_submission: false
use_only_eval: true
optimizer: "adamw_torch"
loss_fn: "cross_entropy"
use_scheduler: true
warmup_ratio: 0.1
lr_scheduler_type: "linear"
train_data_path: ["data/processed/original/clean_train.csv","data/processed/generated/clean_general.csv"]
predict_data_path: "data/processed/clean_test.csv"
label_encoding: "int"
seed: 42
