experiment_name: "ensemble pretrained test"
framework: "pytorch"
num_labels: 5

val_ratio: 0.2
test_ratio: 0.1
save_submission: false

train_data_path: ["data/processed/original/clean_train.csv","data/processed/generated/clean_general.csv"]
predict_data_path: "data/processed/clean_test.csv"
label_encoding: "int"
seed: 42

ensemble:
  strategy: weighted_soft       # soft‐voting
  meta_path: meta_model.pkl     # soft‐voting 시 사용 안 함(스태킹용만 필요)
  models:
    - config_path: configs/config_kobert_no_train.yaml
      weight: 0.5
    - config_path: configs/config_koelectra_no_train.yaml
      weight: 0.5